// Sample Data for Products, Users, and Orders
// Use this to populate your MongoDB database

export const productData = [
  {
    name: "Organic Baby Spinach",
    price: 3.99,
    description:
      "Tender organic baby spinach, triple-washed and ready to cook or toss into salads.",
    images: [
      "https://images.unsplash.com/photo-1506806732259-39c2d0268443?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Fresh Vegetables",
    subCategory: "Organic",
    unit: "pack",
    sizes: ["150g", "300g", "500g"],
    nutritionInfo: {
      calories: 23,
      protein: "2.9g",
      carbs: "3.6g",
      fat: "0.4g",
    },
    origin: "Local farms",
    shelfLife: "3-5 days chilled",
    isOrganic: true,
    bestseller: true,
    inStock: true,
    stockQuantity: 120,
    date: Date.now(),
  },
  {
    name: "Roma Tomatoes",
    price: 2.49,
    description:
      "Juicy Roma tomatoes perfect for sauces, salads, and roasting.",
    images: [
      "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Fresh Vegetables",
    subCategory: "Regular",
    unit: "kg",
    sizes: ["500g", "1kg", "2kg"],
    nutritionInfo: {
      calories: 18,
      protein: "0.9g",
      carbs: "3.9g",
      fat: "0.2g",
    },
    origin: "Mexico",
    shelfLife: "5-7 days chilled",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 200,
    date: Date.now(),
  },
  {
    name: "Alphonso Mangoes",
    price: 12.99,
    description:
      "Sweet, fragrant Alphonso mangoes — the king of fruits in season.",
    images: [
      "https://images.unsplash.com/photo-1615485737455-9f8553c9f523?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Fresh Fruits",
    subCategory: "Premium",
    unit: "kg",
    sizes: ["1kg box", "2kg box"],
    nutritionInfo: {
      calories: 60,
      protein: "0.8g",
      carbs: "15g",
      fat: "0.4g",
    },
    origin: "Ratnagiri, India",
    shelfLife: "3-4 days at room temp",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 80,
    date: Date.now(),
  },
  {
    name: "Blueberry Clamshell",
    price: 4.99,
    description:
      "Fresh blueberries packed with antioxidants, perfect for snacking and smoothies.",
    images: [
      "https://images.unsplash.com/photo-1502744688674-c619d1586c9a?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Fresh Fruits",
    subCategory: "Berries",
    unit: "pack",
    sizes: ["125g", "250g"],
    nutritionInfo: {
      calories: 57,
      protein: "0.7g",
      carbs: "14g",
      fat: "0.3g",
    },
    origin: "Chile",
    shelfLife: "5-7 days chilled",
    isOrganic: false,
    bestseller: false,
    inStock: true,
    stockQuantity: 150,
    date: Date.now(),
  },
  {
    name: "A2 Cow Milk",
    price: 2.79,
    description:
      "Fresh A2 cow milk, homogenized and pasteurized for daily nutrition.",
    images: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Dairy Products",
    subCategory: "Milk",
    unit: "liter",
    sizes: ["500ml", "1L", "2L"],
    nutritionInfo: {
      calories: 61,
      protein: "3.2g",
      carbs: "4.8g",
      fat: "3.3g",
    },
    origin: "Local dairy",
    shelfLife: "4-5 days chilled",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 300,
    date: Date.now(),
  },
  {
    name: "Greek Yogurt",
    price: 5.49,
    description:
      "Thick and creamy Greek yogurt with live cultures, perfect for breakfast bowls.",
    images: [
      "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Dairy Products",
    subCategory: "Yogurt",
    unit: "pack",
    sizes: ["170g", "500g"],
    nutritionInfo: {
      calories: 59,
      protein: "10g",
      carbs: "3.6g",
      fat: "0.4g",
    },
    origin: "USA",
    shelfLife: "10-14 days chilled",
    isOrganic: true,
    bestseller: true,
    inStock: true,
    stockQuantity: 140,
    date: Date.now(),
  },
  {
    name: "Sourdough Bread",
    price: 4.29,
    description:
      "Artisan sourdough loaf with a crisp crust and airy crumb, baked fresh daily.",
    images: [
      "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Bakery Items",
    subCategory: "Bread",
    unit: "loaf",
    sizes: ["600g"],
    nutritionInfo: {
      calories: 240,
      protein: "8g",
      carbs: "46g",
      fat: "2g",
    },
    origin: "Local bakery",
    shelfLife: "2-3 days",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 90,
    date: Date.now(),
  },
  {
    name: "Free-Range Brown Eggs",
    price: 3.59,
    description:
      "Dozen large free-range brown eggs with rich yolks and high protein.",
    images: [
      "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Breakfast",
    subCategory: "Eggs",
    unit: "dozen",
    sizes: ["12 eggs"],
    nutritionInfo: {
      calories: 155,
      protein: "13g",
      carbs: "1.1g",
      fat: "11g",
    },
    origin: "Free-range farms",
    shelfLife: "3 weeks chilled",
    isOrganic: true,
    bestseller: true,
    inStock: true,
    stockQuantity: 180,
    date: Date.now(),
  },
  {
    name: "Cold Brew Coffee Concentrate",
    price: 6.99,
    description:
      "Smooth, low-acid cold brew concentrate — just add milk or water and ice.",
    images: [
      "https://images.unsplash.com/photo-1510626176961-4b37d0b4e904?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Drinks",
    subCategory: "Coffee",
    unit: "bottle",
    sizes: ["500ml"],
    nutritionInfo: {
      calories: 5,
      protein: "0g",
      carbs: "1g",
      fat: "0g",
    },
    origin: "House brew",
    shelfLife: "14 days chilled",
    isOrganic: false,
    bestseller: false,
    inStock: true,
    stockQuantity: 110,
    date: Date.now(),
  },
  {
    name: "Skinless Chicken Breast",
    price: 7.49,
    description:
      "Lean, boneless, skinless chicken breast — trimmed and ready to cook.",
    images: [
      "https://images.unsplash.com/photo-1604908812715-5f020f57f23c?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Meat & Seafood",
    subCategory: "Poultry",
    unit: "kg",
    sizes: ["500g", "1kg"],
    nutritionInfo: {
      calories: 165,
      protein: "31g",
      carbs: "0g",
      fat: "3.6g",
    },
    origin: "Local farms",
    shelfLife: "2-3 days chilled",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 95,
    date: Date.now(),
  },
  // --- New Electronics sector ---
  {
    name: "Ultrabook Pro 14",
    price: 1199.99,
    description:
      "Lightweight 14-inch ultrabook with Intel i7, 16GB RAM, 512GB SSD, 2.8K display, Wi‑Fi 6E, backlit keyboard.",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Laptops",
    unit: "unit",
    sizes: ["i7/16GB/512GB", "i7/32GB/1TB"],
    sizePricing: {
      "i7/16GB/512GB": 1199.99,
      "i7/32GB/1TB": 1499.99,
    },
    sizeStock: {
      "i7/16GB/512GB": 20,
      "i7/32GB/1TB": 15,
    },
    brand: "TechPro",
    model: "UP14-7130",
    warranty: "2 Years Official Warranty",
    specs: {
      Processor: "Intel Core i7-1360P",
      RAM: "16GB LPDDR5",
      Storage: "512GB NVMe SSD",
      Display: '14" 2.8K (2880x1800) 90Hz',
      Graphics: "Intel Iris Xe",
      Weight: "1.25 kg",
      Ports: "2x Thunderbolt 4, HDMI 2.0, Audio combo",
    },
    bestseller: true,
    inStock: true,
    stockQuantity: 35,
    discount: 10,
    date: Date.now(),
  },
  {
    name: "Noise-Canceling Headphones X200",
    price: 299.99,
    description:
      "Wireless over-ear ANC headphones with 40h battery, LDAC, multipoint Bluetooth, and spatial audio.",
    images: [
      "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Headphones",
    unit: "unit",
    sizes: ["One Size"],
    brand: "SoundMax",
    model: "X200 ANC",
    warranty: "12 Months Official Warranty",
    specs: {
      Driver: "40mm dynamic",
      ANC: "Hybrid Active Noise Cancellation",
      Codec: "LDAC / AAC / SBC",
      Battery: "Up to 40h (ANC on)",
      Charge: "USB-C Fast Charge (10 min = 5h)",
      Weight: "265 g",
      Mic: "6-mic array with ENC",
    },
    bestseller: true,
    inStock: true,
    stockQuantity: 120,
    discount: 15,
    date: Date.now(),
  },
  {
    name: "Smart Home Hub Mini",
    price: 89.99,
    description:
      "Compact smart home hub with voice assistant, Matter, Thread border router, and Zigbee bridge built-in.",
    images: [
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Smart Home",
    unit: "unit",
    sizes: ["One Size"],
    brand: "HomeLink",
    model: "HL-MINI",
    warranty: "1 Year Official Warranty",
    specs: {
      Protocols: "Matter, Thread, Zigbee, Wi‑Fi",
      Voice: "Built-in voice assistant",
      Ports: "USB-C power",
      App: "HomeLink App (iOS/Android)",
      Automation: "Routines, schedules, remote control",
    },
    bestseller: false,
    inStock: true,
    stockQuantity: 200,
    discount: 5,
    date: Date.now(),
  },
  // --- New Fashion sector ---
  {
    name: "Men's TechStretch Hoodie",
    price: 79.99,
    description:
      "Moisture-wicking, 4-way stretch hoodie with hidden zip pocket and reflective trims.",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Men",
    unit: "piece",
    sizes: ["S", "M", "L", "XL"],
    bestseller: true,
    inStock: true,
    stockQuantity: 180,
    discount: 20,
    date: Date.now(),
  },
  {
    name: "Women's Minimalist Crossbody",
    price: 129.0,
    description:
      "Premium vegan-leather crossbody with magnetic flap, adjustable strap, and hidden phone slot.",
    images: [
      "https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Accessories",
    unit: "piece",
    sizes: ["One Size"],
    bestseller: true,
    inStock: true,
    stockQuantity: 95,
    discount: 0,
    date: Date.now(),
  },
  {
    name: "Everyday Runner Sneakers",
    price: 110.0,
    description:
      "Lightweight daily trainers with responsive foam, breathable mesh, and reflective accents.",
    images: [
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Shoes",
    unit: "pair",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
    bestseller: false,
    inStock: true,
    stockQuantity: 150,
    discount: 10,
    date: Date.now(),
  },
  // --- Additional Electronics ---
  {
    name: "Galaxy S24 Ultra Smartphone",
    price: 1299.99,
    description:
      "Premium flagship smartphone with 200MP camera, S Pen, 6.8-inch AMOLED display, Snapdragon 8 Gen 3, and 5000mAh battery.",
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Smartphones",
    unit: "unit",
    sizes: ["8GB+256GB", "12GB+512GB", "12GB+1TB"],
    sizePricing: {
      "8GB+256GB": 1199.99,
      "12GB+512GB": 1299.99,
      "12GB+1TB": 1499.99,
    },
    sizeStock: {
      "8GB+256GB": 25,
      "12GB+512GB": 30,
      "12GB+1TB": 10,
    },
    brand: "Samsung",
    model: "Galaxy S24 Ultra",
    warranty: "1 Year Official Warranty",
    specs: {
      Processor: "Snapdragon 8 Gen 3 for Galaxy",
      Display: '6.8" QHD+ Dynamic AMOLED 2X 120Hz',
      Camera: "200MP + 12MP + 10MP + 10MP, 12MP front",
      Battery: "5000mAh, 45W fast charge",
      Connectivity: "5G, Wi‑Fi 7, BT 5.3, NFC",
      Extras: "S Pen, IP68",
    },
    bestseller: true,
    inStock: true,
    stockQuantity: 65,
    discount: 5,
    date: Date.now(),
  },
  {
    name: "4K Smart TV 55-inch",
    price: 599.99,
    description:
      "55-inch 4K UHD Smart TV with HDR10+, Dolby Vision, built-in streaming apps, and voice control.",
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Televisions",
    unit: "unit",
    sizes: ["55-inch"],
    brand: "ViewPlus",
    model: "VP-55UHD",
    warranty: "3 Years Panel Warranty",
    specs: {
      Panel: "VA, 4K UHD, 60Hz",
      HDR: "HDR10+ / Dolby Vision",
      OS: "Android TV 12",
      Audio: "20W speakers, Dolby Audio",
      Ports: "3x HDMI 2.1, 2x USB, eARC",
      Connectivity: "Wi‑Fi, Bluetooth",
    },
    bestseller: true,
    inStock: true,
    stockQuantity: 30,
    discount: 12,
    date: Date.now(),
  },
  {
    name: "Fitness Smartwatch Pro",
    price: 249.99,
    description:
      "Advanced fitness tracker with dual-band GPS, SpO2, HRV, sleep tracking, and 7-day battery life.",
    images: [
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Electronics",
    subCategory: "Wearables",
    unit: "unit",
    sizes: ["40mm", "44mm"],
    brand: "FitCore",
    model: "FW-Pro",
    warranty: "1 Year Official Warranty",
    specs: {
      Display: '1.43" AMOLED, AOD',
      GPS: "Dual-band L1+L5",
      Sensors: "HR, SpO2, HRV, Compass",
      Battery: "Up to 7 days typical",
      Water: "5ATM",
      Connectivity: "BT 5.3",
    },
    bestseller: false,
    inStock: true,
    stockQuantity: 160,
    discount: 8,
    date: Date.now(),
  },
  // --- Additional Fashion ---
  {
    name: "Women's Denim Jacket",
    price: 89.99,
    description:
      "Classic blue denim jacket with vintage wash, button closure, and chest pockets.",
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Women",
    unit: "piece",
    sizes: ["S", "M", "L", "XL"],
    bestseller: true,
    inStock: true,
    stockQuantity: 110,
    discount: 15,
    date: Date.now(),
  },
  {
    name: "Men's Slim Fit Chinos",
    price: 59.99,
    description:
      "Modern slim-fit chino pants in stretch cotton twill with flat front and tapered leg.",
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Men",
    unit: "piece",
    sizes: ["30", "32", "34", "36", "38"],
    bestseller: false,
    inStock: true,
    stockQuantity: 145,
    discount: 10,
    date: Date.now(),
  },
  {
    name: "Leather Ankle Boots",
    price: 139.99,
    description:
      "Premium leather ankle boots with side zip, cushioned insole, and durable rubber sole.",
    images: [
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Shoes",
    unit: "pair",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10"],
    bestseller: true,
    inStock: true,
    stockQuantity: 85,
    discount: 0,
    date: Date.now(),
  },
  {
    name: "Yoga Leggings High-Waist",
    price: 49.99,
    description:
      "High-waisted yoga leggings with moisture-wicking fabric, hidden pocket, and 4-way stretch.",
    images: [
      "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=1200&q=80",
    ],
    category: "Fashion",
    subCategory: "Activewear",
    unit: "piece",
    sizes: ["XS", "S", "M", "L", "XL"],
    bestseller: false,
    inStock: true,
    stockQuantity: 200,
    discount: 20,
    date: Date.now(),
  },
  {
    name: "Atlantic Salmon Fillet",
    price: 14.99,
    description:
      "Fresh Atlantic salmon fillet, rich in omega-3, skin-on for crisp sear.",
    images: [
      "https://images.unsplash.com/photo-1604908177545-02f6687b4446?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Meat & Seafood",
    subCategory: "Seafood",
    unit: "kg",
    sizes: ["250g", "500g", "1kg"],
    nutritionInfo: {
      calories: 208,
      protein: "20g",
      carbs: "0g",
      fat: "13g",
    },
    origin: "Norway",
    shelfLife: "2 days chilled",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 60,
    date: Date.now(),
  },
  {
    name: "Aged Basmati Rice",
    price: 11.49,
    description:
      "2-year aged long-grain basmati rice with aromatic flavor and extra length.",
    images: [
      "https://images.unsplash.com/photo-1477505982272-ead89926a577?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Grains & Cereals",
    subCategory: "Rice",
    unit: "kg",
    sizes: ["1kg", "5kg"],
    nutritionInfo: {
      calories: 365,
      protein: "7.1g",
      carbs: "80g",
      fat: "0.7g",
    },
    origin: "India",
    shelfLife: "12 months",
    isOrganic: false,
    bestseller: false,
    inStock: true,
    stockQuantity: 130,
    date: Date.now(),
  },
  {
    name: "Dry Roasted Almonds",
    price: 8.49,
    description:
      "Crunchy dry roasted almonds without added oil; great snack or topping.",
    images: [
      "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Snacks",
    subCategory: "Nuts",
    unit: "pack",
    sizes: ["200g", "500g"],
    nutritionInfo: {
      calories: 579,
      protein: "21g",
      carbs: "22g",
      fat: "50g",
    },
    origin: "California",
    shelfLife: "6 months",
    isOrganic: true,
    bestseller: false,
    inStock: true,
    stockQuantity: 160,
    date: Date.now(),
  },
  {
    name: "Honey Almond Granola",
    price: 6.79,
    description:
      "Crunchy baked granola with rolled oats, honey, and roasted almonds.",
    images: [
      "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Breakfast",
    subCategory: "Cereal",
    unit: "pack",
    sizes: ["350g", "700g"],
    nutritionInfo: {
      calories: 430,
      protein: "10g",
      carbs: "62g",
      fat: "14g",
    },
    origin: "USA",
    shelfLife: "6 months",
    isOrganic: false,
    bestseller: false,
    inStock: true,
    stockQuantity: 140,
    date: Date.now(),
  },
  {
    name: "Hass Avocado",
    price: 1.99,
    description:
      "Creamy Hass avocado with rich flavor — perfect for toast and salads.",
    images: [
      "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&w=900&q=80",
    ],
    category: "Fresh Fruits",
    subCategory: "Avocado",
    unit: "piece",
    sizes: ["Single", "Pack of 4"],
    nutritionInfo: {
      calories: 160,
      protein: "2g",
      carbs: "9g",
      fat: "15g",
    },
    origin: "Mexico",
    shelfLife: "3-5 days",
    isOrganic: false,
    bestseller: true,
    inStock: true,
    stockQuantity: 170,
    date: Date.now(),
  },
];

export const userData = [
  {
    name: "John Doe",
    email: "john@example.com",
    password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36P4/laSi", // bcrypt hash of "password123"
    cartData: {},
  },
  {
    name: "Jane Smith",
    email: "jane@example.com",
    password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36P4/laSi", // bcrypt hash of "password123"
    cartData: {
      product3: 1,
    },
  },
  {
    name: "Mike Johnson",
    email: "mike@example.com",
    password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36P4/laSi", // bcrypt hash of "password123"
    cartData: {},
  },
  {
    name: "Sarah Williams",
    email: "sarah@example.com",
    password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36P4/laSi", // bcrypt hash of "password123"
    cartData: {
      product4: 3,
      product5: 1,
    },
  },
  {
    name: "Admin User",
    email: "admin@forever.com",
    password: "$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36P4/laSi", // bcrypt hash of "password123"
    cartData: {},
  },
];

export const orderData = [
  {
    userId: "user1_id_here",
    items: [
      { productId: "product1_id", quantity: 2, price: 29.99 },
      { productId: "product2_id", quantity: 1, price: 49.99 },
    ],
    amount: 109.97,
    address: {
      firstName: "John",
      lastName: "Doe",
      email: "john@example.com",
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zipcode: "10001",
      country: "USA",
      phone: "555-0123",
    },
    status: "Order Placed",
    paymentMethod: "Card",
    payment: true,
    date: new Date(),
  },
  {
    userId: "user2_id_here",
    items: [{ productId: "product3_id", quantity: 1, price: 24.99 }],
    amount: 24.99,
    address: {
      firstName: "Jane",
      lastName: "Smith",
      email: "jane@example.com",
      street: "456 Oak Avenue",
      city: "Los Angeles",
      state: "CA",
      zipcode: "90001",
      country: "USA",
      phone: "555-0456",
    },
    status: "Processing",
    paymentMethod: "Card",
    payment: true,
    date: new Date(),
  },
  {
    userId: "user3_id_here",
    items: [{ productId: "product4_id", quantity: 1, price: 39.99 }],
    amount: 39.99,
    address: {
      firstName: "Mike",
      lastName: "Johnson",
      email: "mike@example.com",
      street: "789 Pine Road",
      city: "Chicago",
      state: "IL",
      zipcode: "60601",
      country: "USA",
      phone: "555-0789",
    },
    status: "Shipped",
    paymentMethod: "Card",
    payment: true,
    date: new Date(),
  },
];

// Passwords used in userData (for reference):
// email: john@example.com, password: password123
// email: jane@example.com, password: password123
// email: mike@example.com, password: password123
// email: sarah@example.com, password: password123
// email: admin@forever.com, password: password123
